{
 "title": "Stromzähler Live",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Leistung",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  power_total AS \"Summe\",\n  \"power_phase1\" AS \"Phase 1\",\n  \"power_phase2\" AS \"Phase 2\",\n  \"power_phase3\" AS \"Phase 3\"\nFROM \"stromzähler\"\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Tagesverbrauch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  energy_daily\nFROM current_values\nWHERE\n  id = 0\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Tageskosten",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  energy_daily * 0.295834 + 0.3\nFROM current_values\nWHERE\n  id = 0\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Zählerstand",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  energy\nFROM current_values\nWHERE\n  id = 0\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Tagesverbräuche der letzten Tage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"date\" AS \"time\",\n  energy AS \"Energieverbrauch\"\nFROM tagesverbrauch\nWHERE\n  $__timeFilter(\"date\")\nORDER BY 1"
    }
   ]
  }
 ]
}